Repository Ejiy/jl-laptop, pull requests merged in 2022-11, with the labels that each got.

#33 Boosting statebag conversion
  client/boosting.lua
  server/boosting.lua
  shared/boosting.lua
Labels: enhancement, help wanted

#34 Lazy patch 1
  .vscode/extensions.json
  client/boosting.lua
  client/main.lua
  html/assets/index.css
  html/js/index.js
  locales/en.lua
  server/boosting.lua
  shared/boosting.lua
  svelte-source/src/@types/apps.ts
  svelte-source/src/App.svelte
  svelte-source/src/components/apps/Boosting.svelte
  svelte-source/src/components/apps/Employment.svelte
  svelte-source/src/components/base/Desktop.svelte
  svelte-source/src/components/base/Icons.svelte
  svelte-source/src/components/base/Notification.svelte
  svelte-source/src/components/base/RightSide.svelte
  svelte-source/src/components/base/Winmanager.svelte
  svelte-source/src/components/shared/Apps.svelte
  svelte-source/src/store/employment.ts
  svelte-source/src/store/notifications.ts
  svelte-source/src/store/oldnotification.ts
  svelte-source/src/utils/eventHandler.ts
  svelte-source/src/utils/initDumyData.ts
Labels: enhancement, help wanted, question

#37 Some new additions.
  client/boosting.lua
  client/darkweb.lua
  server/boosting.lua
  shared/boosting.lua
  shared/darkweb.lua
Labels: enhancement
